### ISSUE TITLE
Configure Prisma with SQLite

### ISSUE THREAD

**Issue by cferreirasuazo** [Androbat/library-api#1]
In this first task, you are going to configure Prisma with SQLite and create the entity User. User will have a name, email, password and id. This ID will be generated automatically.

Tip: try to use uuid.

**Comment by Androbat** [comment]
Resource: https://www.prisma.io/docs/getting-started/quickstart

**Comment by cferreirasuazo** [comment]
Eso es hacer trampa corazon bello. Tengo que hacerte el review.
