### ISSUE TITLE
Implement API Name conversion

### ISSUE THREAD

**Issue by cferreirasuazo** [Androbat/library-api#6]
# Implement API Name conversion

You are going to implement a proper name conversation for your API's URIs.  Make sure to make a research on how to implement this requirements. Make sure to get familiar with this conversation. 

Use Postman or Insomnia to make sure the operations are working properly using the following scenarios: 

## Scenarios 

- [x] You can POST to /api/users with data for create a new user
- [x] The returned response from POST /api/users will be the information of the user
- [x] You can make a GET request to /api/users to get a list of all users.
- [x] The GET request to /api/users returns an array.
- [x] Each element in the array returned from GET /api/users is an object literal containing information of the user
- [x] You can DELETE to /api/users/:id in order to delete a user
- [x] /api/products GET should return a list of all products
- [x] /ap/products/:id should return the information of a product using It's ID

## Resources 

Here is a list of resources that you can read
https://restfulapi.net/resource-naming/
https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/
https://medium.com/@nadinCodeHat/rest-api-naming-conventions-and-best-practices-1c4e781eb6a5

**Comment by Androbat** [comment]
By now I've tested:

- Post `/api/users`

**Comment by Androbat** [comment]
Basically there are done but I have to test the last two: get products and get product by id.

**Comment by Androbat** [comment]
Basically all of this task are closed since I finished and tested all of them.
