### ISSUE TITLE
Play with query parameters. 

### ISSUE THREAD

**Issue by cferreirasuazo** [Androbat/library-api#9]
Query parameters are parameters attached to the end of a URL and separated from the URL by a question mark (?).

e.g example.com/api/some/resource?name=John&height=10.

This mechanism allows you to search and filter your information using certain criteria, to represent the current page number in a paginated collection and many other things.

You are going to implement the following query parameters

- [x] /api/products?name=
- [x] /api/products?startPrice=5&endPrice=5 should allow to retrieve products that prices are found in a range.

**Comment by Androbat** [comment]
Check the code in order to close this or improve the code.
